server {
    listen 80;
    server_name localhost;
    
    # Define a pasta raiz onde o Docker colocou seus arquivos
    root /usr/share/nginx/html;
    index index.html;

    # Tenta carregar o arquivo exato, depois tenta como pasta, depois tenta adicionar .html
    location / {
        try_files $uri $uri/ $uri.html =404;
    }

    # === REWRITES ESPECÍFICOS (Tradução do Firebase) ===
    
    rewrite ^/contato$ /paginas/contato/index.html last;
    rewrite ^/sobre$ /paginas/sobre/index.html last;
    rewrite ^/projetos$ /paginas/projetos/index.html last;
    
    # Case único do Transporta e redirecionamento da rota técnica antiga
    location ~ ^/projetos/transporta/tecnica/?$ {
        absolute_redirect off;
        return 301 /projetos/transporta;
    }
    rewrite ^/projetos/transporta/?$ /paginas/projetos/transporta/index.html last;


    # === PÁGINA DE ERRO ===
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
